spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: '---'
            clientSecret: '-----'
            scope:
              - user:email
              - read:user
