spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: '31a44eea6743484ac5f4'
            clientSecret: '118d6ef4f1da6245045aa76adc46e804e6bc8c73'
            scope:
              - user:email
              - read:user